"""update code column length to 2

Revision ID: 4cd1986f79cc
Revises: 93d5164aab8f
Create Date: 2025-11-02 15:13:18.900302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4cd1986f79cc'
down_revision: Union[str, Sequence[str], None] = '93d5164aab8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'code',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=8),
               type_=sa.String(length=2),
               existing_nullable=False)
    op.alter_column('payment_methods', 'code',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=8),
               type_=sa.String(length=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payment_methods', 'code',
               existing_type=sa.String(length=2),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=8),
               existing_nullable=False)
    op.alter_column('categories', 'code',
               existing_type=sa.String(length=2),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=8),
               existing_nullable=False)
    # ### end Alembic commands ###
