"""update transaction type values to 2 chars

Revision ID: 4fe7fb9b8fe0
Revises: 4cd1986f79cc
Create Date: 2025-11-02 15:16:35.838771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4fe7fb9b8fe0'
down_revision: Union[str, Sequence[str], None] = '4cd1986f79cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'transaction_type',
               existing_type=mysql.CHAR(collation='utf8mb4_unicode_ci', length=3),
               type_=sa.CHAR(length=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'transaction_type',
               existing_type=sa.CHAR(length=2),
               type_=mysql.CHAR(collation='utf8mb4_unicode_ci', length=3),
               existing_nullable=False)
    # ### end Alembic commands ###
